; ComfyTyping configuration
;
; Keys are exe names without the .exe extension (case-insensitive).
; Values are human-readable descriptions (ignored by the program).

[default]
ONLY_WHITELISTED = 0 ; 1 to only apply to whitelisted apps

[whitelisted]
code       = VS Code
devenv     = Visual Studio IDE
chrome     = Chrome Browser
msedge     = Microsoft Edge browser
firefox    = Firefox Browser
mintty     = Git Bash
notepad    = Notepad
notepad++  = Notepad++
explorer   = Windows Explorer
cmd        = Command Prompt
powershell = Power Shell
windowsterminal = Command Prompt? Power Shell? Both?


[blacklisted]
;msedge  = MS Edge browser
