; ComfyTyping configuration
;
; Keys are exe names without the .exe extension (case-insensitive).
; Values are human-readable descriptions (ignored by the program).

[default]
ONLY_WHITELISTED = 0    ; If 1, only whitelisted apps are augmented

[whitelisted]
code    = VS Code
devenv  = Visual Studio IDE

[blacklisted]
;msedge  = MS Edge browser
